[1]
Component = "SBEPIS.Player, SBEPIS"
Football = "2"
Camera = "3"

[2]
Prefab = "FootballWithShinGuard.toml"

[3]
Component = "Echidna2.Rendering3D.Camera3D, Echidna2.Rendering3D"
Transform = "4"

[4]
Component = "Echidna2.Rendering3D.Transform3D, Echidna2.Rendering3D"